version: '3.5'

services:
  prestashop:
    build:
      context: ./
      dockerfile: prestashop
    ports:
      - "80:80"
      - "443:443"
      - "9000"
    networks:
      - bridge
    volumes:
      - ../docker/config/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ${PWD}:/var/www/html/
  db:
    build:
      context: ./
      dockerfile: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - bridge
    restart: on-failure
    volumes:
      - ${PWD}/db:/var/lib/mysql:cached
  ftpd_server:
    build:
      context: ./
      dockerfile: ftp
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "${PWD}:/home/ftp/"
      - "/home/ftp/docker"
      - "/home/ftp/db"
      - "/home/ftp/.git"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ftp
      FTP_USER_PASS: 1234
      FTP_USER_HOME: /home/ftp
    restart: always
networks:
  bridge:
    driver: bridge